### PR TITLE
null safety upgrade

### PR DESCRIPTION
**Pull request by yathit**

### CODE REVIEW

**Comment by yathit** [comment]
Null safety support #58  #56

**Comment by yanivshaked** [comment]
How soon can we expect null safety to be merged?

**Comment by yathit** [comment]
Thank you. Please update version to 2.0.0 so that non-null safety user can continue to stay on version 1.

**Comment by zhouteng0217** [comment]
@yathit  @yanivshaked  merged and version 2.0.0 was just released.

**Pull request merged**
