### PR TITLE
Fix content provider

### PR DESCRIPTION
**Pull request by JEuler**
Addresses this issue https://github.com/zhouteng0217/ShareExtend/issues/26

That is the fix for one file share, I don't have need to share multiple files so didn't code it in more flexible way.

### CODE REVIEW

**Comment by JEuler** [comment]
Squashed the bunch of comments :)

**Comment by zhouteng0217** [comment]
@JEuler, It is not necessary to add extra code to grant uri permissions, because ShareExtendProivder has granted uri permissions in AndroidMainfest.xml.  So I think this pr is not necessary.

**Comment by JEuler** [comment]
But with this I am not seeing the 
```
Permission Denial: reading com.zt.shareextend.ShareExtendProvider uri content://kw.ltd.sss.shareextend.fileprovider/root_path/data/data/kw.ltd.corovavirusapp/app_flutter/2020-03-23T16%3A56%3A26.803860.png from pid=6011, uid=1000 requires the provider be exported, or grantUriPermission()
```

**Comment by JEuler** [comment]
https://github.com/zhouteng0217/ShareExtend/issues/26 - if someone can prove that this PR is fixing this, maybe it is okay. But anyway, it is your lib, actually, very nice :)

**Comment by zhouteng0217** [comment]
@JEuler Sorry, I was wrong this time. 

I checked some information about this. There is two ways to grant url permissions.
 One is ```intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)```, but this only works  when passing data by ```intent.setData```、```intent.setDataAndType``` or ```intent.setClipData```. The other way is ```grantUriPermission``` like what you provided.

I will merge the pr soon and later will publish a new version after adding this changes to multiple share.

Thank you for your contribution very much.

**Comment by JEuler** [comment]
@zhouteng0217 Thank you very much for your great library!

**Pull request merged**
